### ISSUE TITLE
Pagamento adicionado com moeda EUR e o valor ainda na moeda original BRL

### ISSUE THREAD

**Issue by kevineduardo** [moloni-pt/whmcs#6]
Usando a última versão do addon, quando um documento é gerado, o mesmo adiciona o pagamento também, mas não faz a conversão para EUR, mantém o valor em BRL, porém fica registrado como EUR.

Por exemplo, um pagamento de cartão no valor de 130 reais (BRL), aparece como 130 euros (EUR) no documento gerado.

**Comment by kevineduardo** [comment]
Fiz o fix.

<img width="723" alt="Captura de ecrã 2024-10-23, às 22 04 09" src="https://github.com/user-attachments/assets/32a58b39-ed11-4748-91cc-eadf525f82cd">

Qualquer coisa, pode copiar essa parte diretamente do meu fork (https://github.com/kevineduardo/moloni-whmcs-addon/commit/88df5ed1d93e63adfe5dec7385214f735dce96fc#diff-f9dd4b581ea0dda9a17983950fa80279987a7584f4e8b54ac20b8037e4480335R560).

**Comment by moloni-pt** [comment]
Bom dia, 

Lançámos já um update para resolver o caso que indicou e, se pretender, poderá agora descarregar a nova versão. 
https://github.com/moloni-pt/whmcs/releases/tag/v8.1.0

Agradecemos que tenha reportado esta situação. 

Cumprimentos.
